name: Preflight Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        id: lint
        run: helm lint
        working-directory: charts/zigbee2mqtt

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          fail-on-diff: true
