name: OnZigbee2MQTTRelease
on:
  workflow_dispatch:
    inputs:
      zigbee2mqtt_version:
        description: 'Version of zigbee2mqtt released'
        required: true
        type: string

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Don't use standard token, otherwise `git push` doesn't trigger `helm_release.yaml`
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.43.1

      - name: Update helm values
        run: |
          ZIGBEE2MQTT_VERSION=${{ github.event.inputs.zigbee2mqtt_version }}
          yq -i ".appVersion=\"${ZIGBEE2MQTT_VERSION}\"" charts/zigbee2mqtt/Chart.yaml
          yq -i ".version=\"${ZIGBEE2MQTT_VERSION}\"" charts/zigbee2mqtt/Chart.yaml
          go run github.com/norwoodj/helm-docs/cmd/helm-docs@latest
          
          git add charts
          git commit -m "chore: Updated chart and app version to ${ZIGBEE2MQTT_VERSION}"
          git push
